{{- if not .Values.bmcCreds.perHost }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: eso-bmc-creds
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: bmc-creds
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.bmcCreds.key }}
{{- else }}
{{- range .Values.bmcCreds.hosts }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: eso-bmc-secret-{{ .name }}
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: bmc-secret-{{ .name }}
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .key }}
{{- end }}
{{- end }}
