apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-klusterlet-addon
  labels:
    {{- include "cluster-deploy-pipelines.labels" . | nindent 4 }}
spec:
  description: Creates KlusterletAddonConfig resource
  params:
  - name: cluster-name
    description: Name of the cluster
    type: string
  - name: cluster-group
    description: Cluster group label
    type: string
    default: "devops"
  steps:
  - name: create-klusterlet-addon
    image: {{ .Values.kubectlImage }}
    script: |
      #!/bin/bash
      set -e
      
      CLUSTER_NAME=$(params.cluster-name)
      CLUSTER_GROUP=$(params.cluster-group)
      
      cat <<EOF | oc apply -f -
      apiVersion: agent.open-cluster-management.io/v1
      kind: KlusterletAddonConfig
      metadata:
        name: $CLUSTER_NAME
        namespace: $CLUSTER_NAME
      spec:
        clusterName: $CLUSTER_NAME
        clusterNamespace: $CLUSTER_NAME
        clusterLabels:
          cloud: auto-detect
          vendor: OpenShift
          clusterGroup: $CLUSTER_GROUP
          cluster.open-cluster-management.io/clusterset: default
        applicationManager:
          enabled: true
        policyController:
          enabled: true
        searchCollector:
          enabled: true
        certPolicyController:
          enabled: true
      EOF
      
      echo "KlusterletAddonConfig $CLUSTER_NAME created"
